[cmake]
version = "3.31"
cmkr-include = "cmkr.cmake"

[project]
name = "GT7 Viewer"
description = "A simple app to view car telemetry from Gran Turismo 7 in real time"
languages = ["C", "CXX"]

[variables]
CMAKE_EXPORT_COMPILE_COMMANDS = true

[target.gt7viewer]
type = "executable" 
sources = [
    "src/**.cpp",
]
include-directories = [
    "src",
]
compile-features = ["cxx_std_23"]
precompile-headers = ["src/pch.hpp"]
